
name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: HashiCorp Vault
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: https://sample-cluster-public-vault-538e9aac.ccf3202b.z1.hashicorp.cloud:8200
          secrets: |
            secret/data/myapp/config SONAR_TOKEN | SONAR_TOKEN ;
            secret/data/myapp/config SNYK_TOKEN | SNYK_TOKEN ;

          namespace: admin
          role: my-role
          token: ${{ secrets.VAULT_TOKEN }}

      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}

      - name: Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        with:
          command: monitor



          
 

          
