
name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk
        uses: snyk/actions@0.4.0
        env:
          SNYK_TOKEN: snyk_uat.1fcad39e.eyJlIjoxNzgwMTYzMTM5LCJoIjoic255ay5pbyIsImoiOiJBWnlxbDJ1WGlPeEMxd25PZTBpTjFnIiwicyI6Ik9XRkJwZ2hKUVAtTDRvMkRyN3I4MFEiLCJ0aWQiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBIn0.Vt8e2fnkegnL7Tzt1ABgJE42oQK7rpuf0tggrX0_Qt8duiG9cuGQp9GeOW1pRTtEkjH6w8IWc8nv8uTa1YyZBw
        with:
          command: test
 

          
